spring:
  profiles.active: development
  pidfile: shared/tmp/pids/eureka-server.pid
eureka:
  environment: production
  instance:
    hostname: localhost
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
---
spring:
  profiles: test
---
spring:
  profiles: production
