spring:
  profiles.active: development
eureka:
  instance:
    hostname: localhost
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
---
spring:
  profiles: test
---
spring:
  profiles: production
