spring:
  profiles.active: development
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Freda-Rally/cooper4-2.0.git
          searchPaths: yamls

  pidfile: shared/tmp/pids/config-server.pid
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
---

spring:
  profiles: test
---
spring:
  profiles: production
