spring:
  profiles.active: development
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Freda-Rally/cooper4-2.0.git
          searchPaths: yamls

  pidfile: shared/tmp/pids/config-server.pid
server:
  port: 8001
---

spring:
  profiles: test
---
spring:
  profiles: production
