spring:
  profiles.active: development

  pidfile: shared/tmp/pids/oauth2-server.pid
#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
---

spring:
  profiles: test
---
spring:
  profiles: production
