spring:
  profiles.active: development

  pidfile: shared/tmp/pids/oauth2-server.pid
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: test
---
spring:
  profiles: production
